[package]
name = "golta-shim"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/suwakei/golta"

[[bin]]
name = "go"
path = "main.rs"

[dependencies]
home = "0.5.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.23.0"