on:
  push:
    tags:
      - "v*.*.*"

name: Deploy

env:
  RELEASE_DIR: release

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./ci/docker
          push: false
          load: true
          tags: volta-ci
      - run: docker run --volume ${PWD}:/root/workspace --workdir /root/workspace --rm --init --tty volta /root/workspace/ci/build-linux.sh volta-linux
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: target/release/volta-linux.tar.gz

  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cross
      - run: cross build --release --target aarch64-unknown-linux-gnu
      - run: |
          cd target/aarch64-unknown-linux-gnu/release
          tar -zcvf volta-linux-arm.tar.gz volta volta-shim volta-migrate
      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm
          path: target/aarch64-unknown-linux-gnu/release/volta-linux-arm.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - run: cargo install --locked cargo-wix --root ./cargo-cache
      - run: cargo wix --nocapture --package volta --output target\wix\volta-windows.msi
      - run: powershell Compress-Archive -Path target/release/volta.exe,target/release/volta-shim.exe,target/release/volta-migrate.exe -DestinationPath target/release/volta-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: target/release/volta-windows.zip

  release:
    needs: [linux, linux-arm, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine version
        id: release_info
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          path: ${{ env.RELEASE_DIR }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          files: |
            ${{ env.RELEASE_DIR }}/linux/volta-linux.tar.gz
            ${{ env.RELEASE_DIR }}/linux-arm/volta-linux-arm.tar.gz
            ${{ env.RELEASE_DIR }}/windows/volta-windows.zip
          fail_on_unmatched_files: true
